name: Release VS Code Extension

on:
  push:
    tags:
      - "vscode-v*"

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        working-directory: ./vscode-extension
        run: |
          npm ci

      - name: Compile
        working-directory: ./vscode-extension
        run: |
          npm run compile

      - name: Package VSIX
        working-directory: ./vscode-extension
        run: |
          npx --no-install @vscode/vsce package --out system-mcp-vscode.vsix

      - name: Create GitHub Release and upload VSIX
        uses: softprops/action-gh-release@v2
        with:
          files: vscode-extension/system-mcp-vscode.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to VS Code Marketplace (optional)
        if: ${{ secrets.VSCE_PAT != '' }}
        working-directory: ./vscode-extension
        run: |
          npx --no-install @vscode/vsce publish -p $env:VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
